services:

  owncloud:
    image: owncloud/server:10.16.0
    container_name: owncloud
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=$domain
      - OWNCLOUD_TRUSTED_DOMAINS=$trust_domain
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=$db_name
      - OWNCLOUD_DB_USERNAME=$db_user
      - OWNCLOUD_DB_PASSWORD=$db_pass
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=$admin_name
      - OWNCLOUD_ADMIN_PASSWORD=$admin_pass
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
      # S3 Object Storage Configuration
      - OWNCLOUD_OBJECTSTORE_ENABLED=true
      - OWNCLOUD_OBJECTSTORE_CLASS=OCA\Files_Primary_S3\S3Storage
      - OWNCLOUD_OBJECTSTORE_BUCKET=$bucket
      - OWNCLOUD_OBJECTSTORE_ENDPOINT=$s3_endpoint
      - OWNCLOUD_OBJECTSTORE_KEY=$s3_access
      - OWNCLOUD_OBJECTSTORE_SECRET=$s3_secret
      - OWNCLOUD_OBJECTSTORE_REGION=ru-1  # Regru typically uses this
      - OWNCLOUD_OBJECTSTORE_PATHSTYLE=true
      - OWNCLOUD_OBJECTSTORE_VERSION=2006-03-01
      # - OWNCLOUD_OBJECTSTORE_PART_SIZE=5242880
      # - OWNCLOUD_OBJECTSTORE_CONCURRENCY=3
      # - OWNCLOUD_OBJECTSTORE_AVAILABLE_STORAGE=
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  mariadb:
    image: mariadb:10.11
    container_name: owncloud_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$db_pass
      - MYSQL_USER=$db_user
      - MYSQL_PASSWORD=$db_pass
      - MYSQL_DATABASE=$db_name
      - MARIADB_AUTO_UPGRADE=1
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=$db_pass"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
       - redis:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    

volumes:
  files:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local






